#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main', 'release']
  workflow_dispatch:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: modbus2mqtt/modbus2mqtt

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/modbus2mqtt.dev
          path: .
      - uses: actions/checkout@v4
        with:
          path: server
      - name: '✏️ Generate changelog'
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: server/CHANGELOG.md
          headerLabel: '# Changelog for ${{github.event.repository.name}}'
      - name: Update sha in package-lock.json
        run: |
          cd server
          npm update @modbus2mqtt/specification.shared @modbus2mqtt/server.shared @modbus2mqtt/angular @modbus2mqtt/specification
      - name: Checkin CHANGELOG.md and package-lock.json 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./server
          commit_message: Update CHANGELOG.md
      - name: Wait for other workflow run or continue
        id: init
        run: |
          gh auth status
          owner=""
          if [ "${{github.event.act.owner}}" != '' ]
          then
            owner="-o ${{github.event.act.owner}}"
          else
            owner="-o ${{github.repository_owner}}"
          fi
          echo "owner=$owner" >> "$GITHUB_OUTPUT"
          bin/pulls.py $owner execorwait --noexec "${{github.event.repository.name}}:${{github.event.number}}" "${{github.event.push.body}}" merge >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: NPM install
        run: |
          #git config --global url."https://github.com/".insteadOf git@github.com:
          #git config --global url."https://".insteadOf git://
          npm init -y
          # HEAD of release or main branch 
          echo "npm install github:modbus2mqtt/server#${{github.ref_name}}"
          npm install --omit=dev "github:modbus2mqtt/server#${{github.ref_name}}"
      - name: Archive node_modules directory artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-node_modules
          path: |
            package.json
            package-lock.json
            node_modules/
            node_modules/.bin/
          retention-days: 1
          include-hidden-files: true
  release:
    runs-on: ${{matrix.platform}}
    environment: release
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04-arm]
    needs: init
    outputs:
      version: ${{steps.prepareAddonDirectory.outputs.TAG_NAME}}
      latest: ${{steps.releasecheck.outputs.latest}}
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Platform check
        id: platformcheck
        run: if [ ${{matrix.platform}} == 'ubuntu-22.04-arm' ]; then echo "platform=arm64"; else echo "platform=amd64";fi >> $GITHUB_OUTPUT
      - name: Release Check
        id: releasecheck
        run: if [ ${{github.ref_name}} != 'release' ]; then echo "latest=.latest"; else echo "latest=";fi >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/modbus2mqtt.dev
          path: .
      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/hassio-addon-repository
          path: hassio-addon-repository
          ref: refs/heads/main
          token: ${{ secrets.PAT }}

      - name: 'create rootfs/usr/app directory'
        run: mkdir -p "hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app"
      - uses: actions/download-artifact@v4
        with:
          name: server-node_modules
          path: hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app
      - name: list hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app
        run: ls -R hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app
      - name: list hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app
        run: ls -R hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Prepare Addon Directory
        id: prepareAddonDirectory
        run: |
          ./bin/releaseAddon.py --ref ${{github.ref}} --pkgjson "hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker/rootfs/usr/app/node_modules/@modbus2mqtt/server" >>$GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{steps.releasecheck.outputs.latest}}-${{steps.platformcheck.outputs.platform}}
          labels: org.opencontainers.image.version=${{steps.prepareAddonDirectory.outputs.TAG_NAME}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/${{steps.platformcheck.outputs.platform}}
          context: hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}/docker
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{steps.releasecheck.outputs.latest}}-${{steps.platformcheck.outputs.platform}}:${{steps.prepareAddonDirectory.outputs.TAG_NAME}}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1    
      - name: Copy CHANGELOG.mds
        run: |
          cd hassio-addon-repository/modbus2mqtt${{steps.releasecheck.outputs.latest}}
          mkdir -p changes
          ls -1 docker/rootfs/usr/app/node_modules/@modbus2mqtt | while read dir
          do 
            mkdir -p changes/$dir
            cp docker/rootfs/usr/app/node_modules/@modbus2mqtt/$dir/CHANGELOG.md changes/$dir
          done 
          cd -
      - name: Checkin hassio-addon-repository
        if: ${{steps.platformcheck.outputs.platform == 'arm64' }} 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./hassio-addon-repository
          tagging_message: ${{steps.prepareAddonDirectory.outputs.TAG_NAME}}
          commit_message: ${{steps.prepareAddonDirectory.outputs.TAG_NAME}}  
  docker-tag:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: release
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        env:
          VERSION: ${{needs.release.outputs.version}}
        run: |
          docker buildx imagetools create -t ghcr.io/modbus2mqtt/${{needs.release.outputs.latest}}:${{env.VERSION}} ghcr.io/modbus2mqtt/modbus2mqtt${{needs.release.outputs.latest}}-arm64:${{env.VERSION}} ghcr.io/modbus2mqtt/modbus2mqtt${{needs.release.outputs.latest}}-amd64:${{env.VERSION}}
          docker buildx imagetools create -t ghcr.io/modbus2mqtt/modbus2mqtt${{needs.release.outputs.latest}}:latest ghcr.io/modbus2mqtt/modbus2mqtt${{needs.release.outputs.latest}}-arm64:${{env.VERSION}} ghcr.io/modbus2mqtt/modbus2mqtt${{needs.release.outputs.latest}}-amd64:${{env.VERSION}}
